name: null
title:  null
logo: https://media.licdn.com/dms/image/v2/C5603AQHJE_tjEjyspg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1618329056958?e=2147483647&v=beta&t=eazGwg4wrMW32SG1UZ30HHFNrXySS1oMsy30AA-UKlw
theme: jekyll-theme-minimal
plugins:
  - jemoji
